apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jerney-frontend
  labels:
    app: {{ .Release.Name }}-jerney-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-jerney-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-jerney-frontend
    spec:
      containers: 
      - name: jerney-frontend
        image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_HOST
          value: "{{ .Release.Name }}-jerney-backend"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
spec:
  selector:
    app: {{ .Release.Name }}-jerney-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080