apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-jerney-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-jerney-backend
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-frontend-service
            port:
              number: 80
