# jerney-app/values.yaml

database:
  image: postgres
  tag: "15"
  password: supersecretpassword
  storage: 8Gi
backend:
  image: potdartapan/jerney-backend
  tag: ddf707a8d6c69afef147d912b58b334bda543a6c
  replicas: 1
  port: 5000
frontend:
  image: potdartapan/jerney-frontend
  tag: ddf707a8d6c69afef147d912b58b334bda543a6c
  replicas: 1
  port: 8080
