# jerney-app/values.yaml

database:
  image: postgres
  tag: "15"
  password: supersecretpassword
  storage: 8Gi
backend:
  image: abhishekf5/jerney-backend
  tag: 8fcaec91cc5e3b4a6cdb4d9a30732abefe552db2
  replicas: 1
  port: 5000
frontend:
  image: abhishekf5/jerney-frontend
  tag: 8fcaec91cc5e3b4a6cdb4d9a30732abefe552db2
  replicas: 1
  port: 8080
