# jerney-app/values.yaml

database:
  image: postgres
  tag: "15"
  password: supersecretpassword
  storage: 8Gi
backend:
  image: potdartapan/jerney-backend
  tag: 6c360e65d696ee23c4d403d20d5e15d8dc9c0d1b
  replicas: 1
  port: 5000
frontend:
  image: potdartapan/jerney-frontend
  tag: 6c360e65d696ee23c4d403d20d5e15d8dc9c0d1b
  replicas: 1
  port: 8080
