# root-app.yaml (lives at the root of your repo)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tapanpotdar/jerney.git
    targetRevision: HEAD
    path: argo/argocd-apps # The folder containing your Child apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true